name: Build LaTeX Documents

on:
  push:
    branches:
      - main  # Puoi specificare i rami che preferisci

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Compilazione del CV in Inglese
      - name: Compile CV-EN
        uses: xu-cheng/latex-action@v3
        with:
          root_file: CV-EN/main.tex
          latexmk_shell_escape: true

      # Step 3: Rinominare il PDF del CV in Inglese
      - name: Rename CV-EN PDF
        run: mv CV-EN/main.pdf CV_EN.pdf

      # Step 4: Compilazione del CV in Italiano
      - name: Compile CV-IT
        uses: xu-cheng/latex-action@v3
        with:
          root_file: CV-IT/main.tex
          latexmk_shell_escape: true

      # Step 5: Rinominare il PDF del CV in Italiano
      - name: Rename CV-IT PDF
        run: mv CV-IT/main.pdf CV_IT.pdf

      # Step 6: Caricare entrambi i PDF come artifact
      - name: Upload PDF files
        uses: actions/upload-artifact@v4
        with:
          name: LaTeX_PDFs
          path: |
            CV_EN.pdf
            CV_IT.pdf
